/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Blanks: typeof import('./src/components/homeTemplate/module/content/blanks/blanks.vue')['default']
    Bulletin: typeof import('./src/components/homeTemplate/module/content/bulletin/bulletin.vue')['default']
    Component: typeof import('./src/components/homeTemplate/module/component/index.vue')['default']
    Content: typeof import('./src/components/homeTemplate/module/content/index.vue')['default']
    CustomerService: typeof import('./src/components/homeTemplate/module/content/customerService/customerService.vue')['default']
    Editor: typeof import('./src/components/homeTemplate/module/editor/index.vue')['default']
    FileNumber: typeof import('./src/components/homeTemplate/module/content/fileNumber/fileNumber.vue')['default']
    Header: typeof import('./src/components/homeTemplate/module/editor/header/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeTemplate: typeof import('./src/components/homeTemplate/index.vue')['default']
    Layout: typeof import('./src/components/layout/layout.vue')['default']
    Navigation: typeof import('./src/components/homeTemplate/module/content/navigation/navigation.vue')['default']
    News: typeof import('./src/components/homeTemplate/module/content/news/news.vue')['default']
    Polyline: typeof import('./src/components/homeTemplate/module/content/polyline/polyline.vue')['default']
    Search: typeof import('./src/components/homeTemplate/module/content/search/search.vue')['default']
    SelectLinkModel: typeof import('./src/components/SelectLinkModel/SelectLinkModel.vue')['default']
    Swiper: typeof import('./src/components/homeTemplate/module/content/swiper/swiper.vue')['default']
    TabCard: typeof import('./src/components/tabsCard/tabCard.vue')['default']
    WeixinOfficial: typeof import('./src/components/homeTemplate/module/content/weixinOfficial/weixinOfficial.vue')['default']
    WexinOfficial: typeof import('./src/components/homeTemplate/module/editor/wexinOfficial/wexinOfficial.vue')['default']
  }
}
