/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Component: typeof import('./src/components/homeTemplate/module/component/index.vue')['default']
    Content: typeof import('./src/components/homeTemplate/module/content/index.vue')['default']
    Editor: typeof import('./src/components/homeTemplate/module/editor/index.vue')['default']
    Header: typeof import('./src/components/homeTemplate/module/editor/header/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeTemplate: typeof import('./src/components/homeTemplate/index.vue')['default']
    Index2: typeof import('./src/components/homeTemplate/index2.vue')['default']
    Layout: typeof import('./src/components/layout/layout.vue')['default']
    Search: typeof import('./src/components/homeTemplate/module/content/search/search.vue')['default']
    Swiper: typeof import('./src/components/homeTemplate/module/content/swiper/swiper.vue')['default']
    TabCard: typeof import('./src/components/tabsCard/tabCard.vue')['default']
  }
}
